# Generated by Django 6.0.2 on 2026-02-22 15:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('VITALS_CHECK', 'Vitals Check'), ('FULL_BODY_CHECK', 'Full Body Check'), ('FOLLOW_UP', 'Follow-up Consultation')], max_length=30)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='dependents.dependent')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
