# Generated by Django 6.0.2 on 2026-02-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='service',
        ),
    ]
