# Generated by Django 6.0.2 on 2026-02-23 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bodyweight', models.CharField(default='50', max_length=10)),
                ('haemoglobin', models.CharField(default='8.7', max_length=10)),
                ('platelets', models.CharField(default='96000', max_length=10)),
                ('blood_pressure', models.CharField(default='90', max_length=10)),
                ('heartbeat', models.CharField(default='90', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
