# Generated by Django 6.0.2 on 2026-02-23 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('haemoglobin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('platelets', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=7)),
                ('heartbeat', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
